bm/bookmarks/urls.py
from django.conf.urls import patterns, include, url
from bm.bookmarks.views import BookmarkListView, BookmarkCreateView, BookmarkUpdateView, BookmarkDetailView


urlpatterns = patterns('',
    url(r'^$', BookmarkListView.as_view(), name='bookmarks_index'),
    url(r'^add$', BookmarkCreateView.as_view(), name='bookmark_create'),
    url(r'^(?P<pk>\d+)/$', BookmarkDetailView.as_view(), name='bookmark_detail'),
    url(r'^(?P<pk>\d+)/edit/$', BookmarkUpdateView.as_view(), name='bookmark_update'),
    url(r'^fetchtitle$', 'bm.bookmarks.views.fetch_url_title'),
)

bm/news/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',

)

bm/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin
from bm.bookmarks.views import UserBookmarkListView, UserBookmarkDetailView


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'bm.views.index', name='index'),
    url(r'^about/', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/', TemplateView.as_view(template_name='contact.html'), name='contact'),
    url(r'^bookmarks/', include('bm.bookmarks.urls')),
    url(r'^news/', include('bm.news.urls')),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='login'),
    url(r'^accounts/logout/$','django.contrib.auth.views.logout', {'next_page': '/accounts/login/'}, name='logout'),
    url(r'^admin/', include(admin.site.urls)),
    # Default to showing a user's bookmarks
    url(r'^(\w+)/$', UserBookmarkListView.as_view(), name='user_bookmarks'),
    url(r'^(\w+)/bookmarks/$', UserBookmarkListView.as_view(), name='user_bookmarks'),
    url(r'^(?P<username>\w+)/bookmarks/(?P<pk>\d+)/$', UserBookmarkDetailView.as_view(), name='user_bookmark_detail'), 
)

bm/bookmarks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager


class Category(models.Model):
    name = models.TextField()
    description = models.TextField()
    
    def __unicode__(self):
        return self.name

class Bookmark(models.Model):
    url = models.URLField(null=True, blank=True)
    title = models.CharField(max_length=200)
    notes = models.TextField(null=True, blank=True)
    private = models.BooleanField(default=True)
    tags = TaggableManager(blank=True)
    user = models.ForeignKey(User)
    create_date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, null=True)
    entry_date = models.DateTimeField(auto_now_add=True)
    entry_date.editable = True
    
    class Meta:
        ordering = ['-entry_date']
    
    def __unicode__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('bookmark_detail', kwargs={'pk': self.pk})

bm/news/models.py
from django.db import models
from django.contrib.auth.models import User


class NewsItem(models.Model):
    title = models.CharField(max_length=200)
    details = models.TextField(null=True, blank=True)
    user = models.ForeignKey(User)
    create_date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-create_date']
    
    def __unicode__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('news_item', kwargs={'pk': self.pk})

bm/bookmarks/forms.py
from django.forms import ModelForm
from bm.bookmarks.models import Bookmark


class BookmarkForm(ModelForm):
    class Meta:
        model = Bookmark
        exclude = ('user',)

bm/bookmarks/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView
from braces.views import LoginRequiredMixin
from bm.bookmarks.forms import BookmarkForm
from bm.bookmarks.models import Bookmark
from BeautifulSoup import BeautifulSoup
import requests


def fetch_url_title(request):
    title = ''
    try:
        url = request.GET.get('url', '')
        if url:
            result = requests.get(url)
            if result and result.status_code == 200:
                soup = BeautifulSoup(result.content)
                if soup.title:
                    title = soup.title.string
    except Exception as e:
        print 'unexpected fetch_url_title error: %s' % e
    
    return HttpResponse(title)

def add_filters(request, queryset):
    """Adds any request query string parameter filters to a queryset."""
    tag = request.GET.get('tag', '')
    
    if tag:
        queryset = queryset.filter(tags__name__in=[tag])
    
    return queryset

class BookmarkCreateView(LoginRequiredMixin, CreateView):
        model = Bookmark
        form_class = BookmarkForm
        success_url = '/bookmarks/'
        
        def form_valid(self, form):
            form.instance.user = self.request.user
            messages.success(self.request, 'Bookmark added.')
            return super(BookmarkCreateView, self).form_valid(form)

class BookmarkUpdateView(LoginRequiredMixin, UpdateView):
        model = Bookmark
        form_class = BookmarkForm
        success_url = '/bookmarks/'

class BookmarkDetailView(LoginRequiredMixin, DetailView):
    model = Bookmark
    
class BookmarkListView(LoginRequiredMixin, ListView):
    paginate_by = 20
    
    def get_queryset(self):
        qs = Bookmark.objects.filter(user=self.request.user)
        qs = add_filters(self.request, qs)
        
        return qs.order_by('-entry_date')

class UserBookmarkDetailView(DetailView):
    model = Bookmark
    
    def get_object(self):
        #return Bookmark.objects.get(pk=self.kwargs['pk'], private=False)
        return get_object_or_404(Bookmark, pk=self.kwargs['pk'], private=False)

class UserBookmarkListView(ListView):
    paginate_by = 20
    
    def get_context_data(self, **kwargs):
            context = super(ListView, self).get_context_data(**kwargs)
            context.update({
                'specified_user': self.args[0],
            })
            return context
    
    def get_queryset(self):
        user = get_object_or_404(User, username__iexact=self.args[0])
        qs = Bookmark.objects.filter(user=user).filter(private=False)
        qs = add_filters(self.request, qs)

        return qs.order_by('-entry_date')

bm/news/views.py
# Create your views here.

bm/views.py
from django.shortcuts import render, redirect
from bm.news.models import NewsItem


def index(request):
    if request.user.is_authenticated():
        return redirect('bookmarks_index')
    
    news = NewsItem.objects.all().order_by('-create_date')[0:5]
    
    return render(request, 'index.html', {'news': news})

bm/templates/bookmarks/bookmark_detail.html
{% extends "layout.html" %}
{% load humanize %}
{% load markup %}

{% block title %}
{{ object.title }}
{% endblock %}

{% block content %}

<h2>{{ object.title }}</h2>

{% if request.GET.tag %}
<h4><a class="close pull-left" href="{{ request.path }}">&times;</a> &nbsp; Tag: {{ request.GET.tag }}</h4>
{% endif %}

<div class="object{% if object.private %} private-bookmark{% endif %}">
    <h4>
        {% if object.tags.all %}
        <i class="fa fa-tag"></i>
        {% for tag in object.tags.all %} <a href="{{ request.path }}?tag={{ tag }}">{{ tag }}</a> {% endfor %}
        {% endif %}
    </h4>
    <h5>
        <span class="bookmark-list-date" title="{{ object.entry_date|date:"m/d/Y h:i a" }} (UTC)">{{ object.entry_date|naturaltime }}</span>
        {% if object.user == user %}
        <a href="{% url bookmark_update object.id %}">Edit</a>
        {% endif %}
    </h5>
    
    {{ object.notes|markdown:"safe" }}
</div>

{% endblock %}

bm/templates/bookmarks/bookmark_form.html
{% extends "layout.html" %}

{% block title %}
{% if not object %}Add{% else %}Edit{% endif %} Bookmark
{% endblock %}

{% block head %}
        <link rel="stylesheet" href="{{ STATIC_URL }}css/datepicker.css" type="text/css" charset="utf-8"/>
{% endblock %}

{% block content %}

<h2>{% if not object %}Add{% else %}Edit{% endif %} Bookmark</h2>

<div class="row">
    <div class="col-lg-6">
        <div class="well">
            <form method="post" action="">
            {% csrf_token %}

            {{ form.non_field_errors }}
            <table id="bookmark-form-table">
            <tr>
                <th><label for="id_category">Category:</label></th>
                <td>
                    <select name="category" id="id_category">
                        <option value="1" {% if bookmark.category.id == 1 %}selected="selected"{% endif %}>Bookmark</option>
                        <option value="2" {% if bookmark.category.id == 2 %}selected="selected"{% endif %}>Note</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td><label for="id_entry_date">Entry Date:&nbsp;</label></td>
                <td>
                    {{ form.entry_date.errors }}
                    <input id="id_entry_date" type="text" name="entry_date" maxlength="200" value="{{ form.entry_date.value|date:"Y-m-d" }}" />
                </td>
            </tr>
            <tr>
                <td><label for="id_url">Url:</label></td>
                <td>
                    {{ form.url.errors }}
                    <input id="id_url" type="text" name="url" maxlength="200" value="{{ form.url.value|default:"" }}" />
                </td>
            </tr>
            <tr>
                <td><label for="id_title">Title:</label></td>
                <td>
                    {{ form.title.errors }}
                    {{ form.title }}
                    <input type="button" id="fetch_button" class="btn btn-primary btn-sm" value="Fetch Title" onClick="fetchTitle();" data-loading-text="Fetching..." />
                </td>
            </tr>
            <tr>
                <td valign="top"><label for="id_notes">Notes:</label></td>
                <td>
                    {{ form.notes.errors }}
                    {{ form.notes }}
                </td>
            </tr>
            <tr>
                <td><label for="id_private">Private:</label></td>
                <td valign="top">{{ form.private }}</td>
            </tr>
            <tr>
                <td>
                    <label for="id_tags">Tags:</label> 
                </td>
                <td>
                    {{ form.tags.errors }}
                    {{ form.tags }}
                </td>
            </tr>
            </table>
            
            <p><button id="save_button" type="submit" onclick="save();" class="btn btn-primary">Save</button></p>
            
            </form>
        </div>
    </div>
</div>

{% endblock %}

{% block js %}
<script src="{{ STATIC_URL }}js/bootstrap-datepicker.js"></script>

<script type="text/javascript">
function save() {
    $('#save_button').addClass('disabled').text('Saving...');
}

$(document).ready(function() {
    $("#id_url").focus();
    $('#id_entry_date').datepicker({ format: 'yyyy-mm-dd' }).on('changeDate', function(ev){ $('#id_entry_date').datepicker('hide'); });
});
</script>
{% endblock %}

bm/templates/bookmarks/bookmark_list.html
{% extends "layout.html" %}
{% load humanize %}
{% load markup %}

{% block title %}
{% if specified_user %}{{ specified_user }}'s {% endif %}Logbook
{% endblock %}

{% block content %}
<h2>{% if specified_user %}{{ specified_user }}'s {% else %}Your {% endif %}Logbook</h2>

{% if request.GET.tag %}
<h4><a class="close pull-left" href="{{ request.path }}">&times;</a> &nbsp; Tag: {{ request.GET.tag }}</h4>
{% endif %}

<div id="bookmark-list">
{% if object_list %}
    {% for bookmark in object_list %}
    <div class="bookmark{% if bookmark.private %} private-bookmark{% endif %}">
        {% if bookmark.category.name == 'Bookmark' %}
        <h1><a href="{{ bookmark.url }}">{{ bookmark.title }}</a></h1>
        {{ bookmark.notes|markdown:"safe" }}
        {% else %}
            {% if bookmark.user == user %}
            <h1><a href="{% url bookmark_detail bookmark.id %}">{{ bookmark.title }}</a></h1>
            {% else %}
            <h1><a href="/{{ bookmark.user.username }}/bookmarks/{{ bookmark.id }}/">{{ bookmark.title }}</a></h1>
            {% endif %}
        {% endif %}
        <h3>
            {% if bookmark.tags.all %}
            <i class="fa fa-tag"></i>
            {% for tag in bookmark.tags.all %} <a href="{{ request.path }}?tag={{ tag }}">{{ tag }}</a> {% endfor %}
            {% endif %}
        </h3>
        <h4>
            <span class="bookmark-list-date" title="{{ bookmark.entry_date|date:"m/d/Y h:i a" }} (UTC)">{{ bookmark.entry_date|naturaltime }}</span>
            {% if bookmark.user == user %}
            <a href="{% url bookmark_update bookmark.id %}">Edit</a>
            {% endif %}
        </h4>
    </div>
    {% endfor %}
    
    <p id="bookmark-pager">
       {% if page_obj.has_previous %}
           <a class="pager-prev" href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-arrow-circle-o-left"></i> Page {{ page_obj.previous_page_number }}</a> 
       {% endif %}

       {% if page_obj.has_next %}
           <a class="pager-next" href="?page={{ page_obj.next_page_number }}">Page {{ page_obj.next_page_number }} <i class="fa fa-arrow-circle-o-right"></i></a>
       {% endif %}
    </p>
{% else %}
    <p>No bookmarks yet.</p>
{% endif %}
</div>

{% endblock %}

bm/templates/bookmarks/home.html
{% extends "layout.html" %}

{% block content %}
<h1>Hello, world!</h1>
{% endblock %}

bm/templates/bookmarks/save_bookmark.html
{% extends "layout.html" %}

{% block content %}
<h1>Save Bookmark</h1>

<form method="post" action="">
{% csrf_token %}

{{ form.as_p }}

<p><input type="submit" value="Save" /></p>
</form>

{% endblock %}

bm/templates/contact.html
{% extends "layout.html" %}

{% block content %}
<h3>This is the contact page placeholder.</h3>
{% endblock %}

bm/templates/index.html
{% extends "layout.html" %}

{% block content %}

<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
        <div class="jumbotron">
            <h2>Logbook</h2>
            <p>Logbook is a personal project by <a href="http://mikejanger.net">Mike Janger</a> for 
               keeping track of bookmarks and notes.</p>
             
            <p>&nbsp;</p>

            <p>You can see what an account's logbook looks like <a href="/mj/bookmarks/">here</a>, or 
               browse the source on <a href="https://github.com/inchingforward/bm">GitHub</a>.</p>
        </div>
    <div class="col-bg-3"></div>
</div>

{% if news %}
<div id="news" class="span3 pull-right">
    <h1>News</h2>
    {% for news_item in news %}
    <h2>{{ news_item.title }}</h2>
    <h3>{{ news_item.create_date|date:"F d, Y" }}</h3>
    <p>{{ news_item.details }}</p>
    {% endfor %}
</div>
{% endif %}

{% if GOOGLE_ANALYTICS_ID %}
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '{{ GOOGLE_ANALYTICS_ID }}']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
{% endif %}

{% endblock %}

bm/templates/layout.html
{% load url from future %}
<!doctype html>
<html>
<head>
    <title>Logbook | {% block title %}Home{% endblock %}</title>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css" type="text/css" charset="utf-8"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.3.flatly.min.css" type="text/css" charset="utf-8"/>
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    {% block head %}{% endblock %}
</head>
<body>
{% block nav %}
<div class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Logbook</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                {% if user.is_authenticated %}<li><a href="/bookmarks/add">Add</a></li>{% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}">Logout {{ user.username }}</a></li>
            {% else %}
                <li><a href="{% url 'login' %}">Login</a></li>
            {% endif %}
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>
{% endblock %}
<div class="container">
{% if messages %}
{% for message in messages %}
    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
     {{ message }}
    </div>
{% endfor %}
{% endif %}
{% block content %}<h3>You need to override the content block.</h3>{% endblock %}
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="{{ STATIC_URL }}js/bm.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap.3.0.2.min.js"></script>
{% block js %}{% endblock %}

</body>
</html>

bm/templates/login.html
{% extends "layout.html" %}
{% load url from future %}

{% block content %}

<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
        <h2>Log In</h2>
        <div class="well">
            {% if form.errors %}
            <p align="center" class="text-danger">Your username and password didn't match. Please try again.</p>
            {% endif %}
            
            <form id="login-form" method="post" action="{% url 'django.contrib.auth.views.login' %}">
            {% csrf_token %}

            <table align="center" width="50%">
            <tr>
                <th>{{ form.username.label_tag }}</th>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <th>{{ form.password.label_tag }}</th>
                <td>{{ form.password }}</td>
            </tr>
            <tr><td colspan="2">&nbsp;</td></tr>
            <tr>
                <td colspan="2" align="center">
                    <input type="submit" class="btn btn-primary" value="Log In" />
                </td>
            </tr>
            </table>

            <input type="hidden" name="next" value="/bookmarks/" />

            </form>
        </div>
    </div>
    <div class="col-lg-3"></div>
</div>

{% endblock %}

{% block js %}
<script type="text/javascript">
$(document).ready(function() {
    $("#id_username").focus();
});
</script>
{% endblock %}

bm/templates/logout.html
{% extends "layout.html" %}
{% load url from future %}

{% block content %}

<h2>Log In</h2>

{% if form.errors %}
<p align="center" class="text-error">Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}

<table align="center" width="50%">
<tr>
    <th>{{ form.username.label_tag }}</th>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <th>{{ form.password.label_tag }}</th>
    <td>{{ form.password }}</td>
</tr>
<tr>
    <td colspan="2" align="center">
        <input type="submit" class="btn btn-primary" value="Log In" />
    </td>
</tr>
</table>

<input type="hidden" name="next" value="/" />

</form>

<script type="text/javascript">
$(document).ready(function() {
    $("#id_username").focus();
});
</script>
{% endblock %}